name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [closed]

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    ECR_REPO: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECR_REPOSITORY_URI }}
    ECR_REPO_NAME: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECR_REPOSITORY_NAME }}
    CLUSTER: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_CLUSTER_NAME }}
    SERVICE: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_SERVICE_NAME }}
    TASK_DEF: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_TASK_DEFINITION }}

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache Bun dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      .bun
                      node_modules
                  key: bun-deps-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      bun-deps-

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install Bun
              run: curl -fsSL https://bun.sh/install | bash
              env:
                  BUN_INSTALL: /home/runner/.bun

            - name: Add Bun to PATH
              run: echo "/home/runner/.bun/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: bun install

            - name: Run ESLint
              run: bun run lint

            - name: Run Prettier
              run: bun run fmt:check

    build-and-deploy:
        needs: lint-and-format
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v4

            # Configure AWS credentials FIRST
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            # Setup Docker Buildx with caching
            - uses: docker/setup-buildx-action@v2
              with:
                  driver-opts: |
                      image=moby/buildkit:latest
                      network=host

            # ECR Login AFTER AWS credentials
            - name: Login to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2

            # Build and push Docker image
            - name: Build and Push Docker Image
              run: |
                  IMAGE_TAG=$(date +%s)
                  echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

                  docker buildx build \
                    --platform linux/arm64 \
                    -t $ECR_REPO:$IMAGE_TAG \
                    -t $ECR_REPO:latest \
                    --cache-from type=registry,ref=$ECR_REPO:buildcache \
                    --push .

            # Cleanup old images (keep last 3)
            - name: Prune Old Images
              continue-on-error: true
              run: |
                  # Delete all but last 3 tagged images (run in background)
                  (
                    aws ecr list-images \
                      --repository-name $ECR_REPO_NAME \
                      --query 'imageIds[?type(imageTag)!=`null`].imageTag' \
                      --output text \
                      | sort -r \
                      | tail -n +4 \
                      | xargs -P 5 -I {} aws ecr batch-delete-image \
                          --repository-name $ECR_REPO_NAME \
                          --image-ids imageTag={}
                  ) &

            # Update ECS Service
            - name: Update ECS Service
              run: |
                  # Get the current task definition revision
                  ecs_task_definition=$(aws ecs describe-task-definition \
                    --task-definition ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_TASK_DEFINITION }} \
                    --query "taskDefinition.revision" \
                    --output text)

                  # Update ECS service with the new task definition
                  aws ecs update-service \
                    --cluster ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_CLUSTER_NAME }} \
                    --service ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_SERVICE_NAME }} \
                    --force-new-deployment \
                    --task-definition $ecs_task_definition \
                    --deployment-configuration maximumPercent=200,minimumHealthyPercent=50

                  # Wait for the service to stabilize (optional: add max-attempts and shorter delay to speed it up)
                  aws ecs wait services-stable \
                    --cluster ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_CLUSTER_NAME }} \
                    --services ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_SERVICE_NAME }} \
                    --max-attempts 10 \
                    --waiter-delay 10
