name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [closed]

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    ECR_REPO: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECR_REPOSITORY_URI }}
    CLUSTER: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_CLUSTER_NAME }}
    SERVICE: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_SERVICE_NAME }}

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache Bun dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      .bun
                      node_modules
                  key: bun-deps-${{ hashFiles('**/bun.lockb') }}

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install Bun
              run: curl -fsSL https://bun.sh/install | bash
              env:
                  BUN_INSTALL: /home/runner/.bun

            - name: Add Bun to PATH
              run: echo "/home/runner/.bun/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: bun install

            - name: Run ESLint
              run: bun run lint

            - name: Run Prettier
              run: bun run fmt:check

    build-and-deploy:
        needs: lint-and-format
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v4

            # Configure AWS credentials FIRST
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.EASTLEIGH_REAL_ESTATE_ECS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ env.ECR_REPO }}:latest
                  platforms: linux/arm64

            - name: Force Deployment
              run: |
                  aws ecs update-service \
                    --cluster $CLUSTER \
                    --service $SERVICE \
                    --force-new-deployment
